table netflix_clean
	lineageTag: 43a335bb-eadf-45f7-ba8c-1a98eaebb02d

	measure qtd_adulto = CALCULATE([titulos_unicos],netflix_clean[classificacao] = "Adulto")
		formatString: 0
		lineageTag: 14901521-e2ed-4bb8-8faf-47c9604a3e7d

	measure qtd_adolescente = CALCULATE([titulos_unicos], netflix_clean[classificacao] = "Adolescente")
		formatString: 0
		lineageTag: bc8a700b-eed5-49f5-ae28-657de7844bd9

	measure qtd_infantil = CALCULATE([titulos_unicos], netflix_clean[classificacao] = "Infantil")
		formatString: 0
		lineageTag: 8ef9c45a-a275-4572-ad77-210fe4c4462a

	measure 'Publico Predominante' = VAR MaiorValor = MAX([qtd_adulto], MAX([qtd_adolescente], [qtd_infantil])) RETURN SWITCH(TRUE(), MaiorValor = [qtd_adulto], "Adulto", MaiorValor = [qtd_adolescente], "Adolescente", MaiorValor = [qtd_infantil],  "Infantil", "Variado")
		lineageTag: 2f7e7245-d815-437e-90d4-cf90a5fd237a

	measure catalogo_crescimento
		lineageTag: 673e63ec-6cf3-4312-aeb5-79aed461cf0b

	measure crescimento_acumulado = CALCULATE([titulos_unicos], FILTER(ALLSELECTED(netflix_clean), netflix_clean[ano_lancamento]<= MAX(netflix_clean[ano_lancamento])))
		formatString: 0
		lineageTag: d85e22bb-33c4-4392-8c4c-f2288829fc52

	measure distribuicao_publico_alvo = VAR totalTitulosContexto = [titulos_unicos] VAR totalTitulosPorPublico = CALCULATE([titulos_unicos], ALL(netflix_clean[publico_alvo])) RETURN DIVIDE(totalTitulosContexto, totalTitulosPorPublico, 0)
		lineageTag: 8d44c55c-0c40-483d-9bd5-a8f3ec8af3c8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure titulos_unicos =
			
			
			COUNTROWS(
			    VALUES(netflix_clean[id_conteudo])
			)
		formatString: 0
		lineageTag: 24aee179-2ffe-43c5-b37d-c4e87a76d66f

	measure media_filmes = CALCULATE(AVERAGE(netflix_clean[duracao_valor]), netflix_clean[tipo_midia] = "Filme")
		formatString: 0
		lineageTag: cfa5f17f-bf17-43e9-a3da-5e9139b062be

	measure media_series = CALCULATE(AVERAGE(netflix_clean[duracao_valor]),netflix_clean[tipo_midia] = "Série")
		lineageTag: edda10cb-6ce4-4d68-a26d-65f721ebe128

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Filmes = CALCULATE([titulos_unicos], netflix_clean[tipo_midia] = "Filme")
		formatString: 0
		lineageTag: 613fadd8-f006-4444-803d-4407a5892fd3

	measure Séries = CALCULATE([titulos_unicos], netflix_clean[tipo_midia] = "Série")
		formatString: 0
		lineageTag: 00a53ca9-1e50-48d7-b061-9de3741bf9c1

	column id_conteudo
		dataType: string
		lineageTag: 815b075e-0a8e-4e58-aa37-4b4d822fceb2
		summarizeBy: none
		sourceColumn: id_conteudo

		annotation SummarizationSetBy = Automatic

	column titulo
		dataType: string
		lineageTag: ae7e1f4f-5b2e-4301-bafb-f2afc607be0f
		summarizeBy: none
		sourceColumn: titulo

		annotation SummarizationSetBy = Automatic

	column tipo_midia
		dataType: string
		lineageTag: 273cf1e6-92ee-48b3-b6b9-17cf5e8edf92
		summarizeBy: none
		sourceColumn: tipo_midia

		annotation SummarizationSetBy = Automatic

	column diretor
		dataType: string
		lineageTag: ea6a55fa-e3f8-476e-9b80-4384a6878acd
		summarizeBy: none
		sourceColumn: diretor

		annotation SummarizationSetBy = Automatic

	column elenco
		dataType: string
		lineageTag: bedfbf6e-92c8-4fbc-b31c-6e3ebf57f01f
		summarizeBy: none
		sourceColumn: elenco

		annotation SummarizationSetBy = Automatic

	column pais
		dataType: string
		lineageTag: a79e4cd6-5636-4b42-b17b-bd8a8cf79f3a
		summarizeBy: none
		sourceColumn: pais

		annotation SummarizationSetBy = Automatic

	column data_adicao
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3cf3b60d-f9c9-47bb-86de-a7efeade859d
		summarizeBy: none
		sourceColumn: data_adicao

		variation Variation
			isDefault
			relationship: 72f72b2f-ce0a-41bd-a522-32d1a08d31f6
			defaultHierarchy: LocalDateTable_4a53c1cc-7a07-45f5-a01a-158038aa2680.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ano_lancamento
		dataType: int64
		formatString: 0
		lineageTag: 41a87443-8add-44c3-9a54-a5fc16a8d2c3
		summarizeBy: none
		sourceColumn: ano_lancamento

		annotation SummarizationSetBy = User

	column geracao_conteudo
		dataType: string
		lineageTag: 2ebdd756-6e9c-4be8-a2e3-945af04e223b
		summarizeBy: none
		sourceColumn: geracao_conteudo

		annotation SummarizationSetBy = Automatic

	column classificacao
		dataType: string
		lineageTag: 4bdef705-73fa-44e9-9fe2-802671c9379f
		summarizeBy: none
		sourceColumn: classificacao

		annotation SummarizationSetBy = Automatic

	column publico_alvo
		dataType: string
		lineageTag: e34165d6-fe39-4fd1-90d4-e94b9dc969d2
		summarizeBy: none
		sourceColumn: publico_alvo

		annotation SummarizationSetBy = Automatic

	column duracao_valor
		dataType: int64
		formatString: 0
		lineageTag: 5d95b98d-3fbe-4f2c-b027-a454bed85bc8
		summarizeBy: none
		sourceColumn: duracao_valor

		annotation SummarizationSetBy = User

	column duracao_unidade
		dataType: string
		lineageTag: 3fa01d51-d5b5-48cf-9763-8a51bee6579d
		summarizeBy: none
		sourceColumn: duracao_unidade

		annotation SummarizationSetBy = Automatic

	partition netflix_clean = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\freit\OneDrive\Documentos\SQL-Pratica\netflix_db\netflix_clean.xlsx"), null, true),
				    netflix_clean_Sheet = Fonte{[Item="netflix_clean",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(netflix_clean_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"id_conteudo", type text}, {"titulo", type text}, {"tipo_midia", type text}, {"diretor", type text}, {"elenco", type text}, {"pais", type text}, {"data_adicao", type date}, {"ano_lancamento", Int64.Type}, {"geracao_conteudo", type text}, {"classificacao", type text}, {"publico_alvo", type text}, {"duracao_valor", Int64.Type}, {"duracao_unidade", type text}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado", each true),
				    #"Dividir Coluna por Delimitador" = Table.ExpandListColumn(Table.TransformColumns(#"Linhas Filtradas", {{"pais", Splitter.SplitTextByDelimiter(", ", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "pais"),
				    #"Valor Substituído" = Table.ReplaceValue(#"Dividir Coluna por Delimitador","","Pais Não Informado",Replacer.ReplaceValue,{"pais"})
				in
				    #"Valor Substituído"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

